# Generated by Django 3.2.4 on 2021-06-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compra_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccionenvio',
            name='entregado',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
